//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.KFWCFServiceLibrary {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsuranceCalc", Namespace="http://schemas.datacontract.org/2004/07/KFWCFServiceLibrary.Models")]
    [System.SerializableAttribute()]
    public partial class InsuranceCalc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BeginningDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KF.KFWCFServiceLibrary.Car CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CarChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CarNewPriceDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KF.KFWCFServiceLibrary.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExcessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ExcessDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FullPriceWithDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FullPriceWithoutDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KF.KFWCFServiceLibrary.Insurance[] InsurancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SeniorityDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YearsWithoutCrashDiscountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginningDate {
            get {
                return this.BeginningDateField;
            }
            set {
                if ((this.BeginningDateField.Equals(value) != true)) {
                    this.BeginningDateField = value;
                    this.RaisePropertyChanged("BeginningDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KF.KFWCFServiceLibrary.Car Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CarChange {
            get {
                return this.CarChangeField;
            }
            set {
                if ((this.CarChangeField.Equals(value) != true)) {
                    this.CarChangeField = value;
                    this.RaisePropertyChanged("CarChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CarNewPriceDiscount {
            get {
                return this.CarNewPriceDiscountField;
            }
            set {
                if ((this.CarNewPriceDiscountField.Equals(value) != true)) {
                    this.CarNewPriceDiscountField = value;
                    this.RaisePropertyChanged("CarNewPriceDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KF.KFWCFServiceLibrary.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Excess {
            get {
                return this.ExcessField;
            }
            set {
                if ((this.ExcessField.Equals(value) != true)) {
                    this.ExcessField = value;
                    this.RaisePropertyChanged("Excess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ExcessDiscount {
            get {
                return this.ExcessDiscountField;
            }
            set {
                if ((this.ExcessDiscountField.Equals(value) != true)) {
                    this.ExcessDiscountField = value;
                    this.RaisePropertyChanged("ExcessDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FullPriceWithDiscount {
            get {
                return this.FullPriceWithDiscountField;
            }
            set {
                if ((this.FullPriceWithDiscountField.Equals(value) != true)) {
                    this.FullPriceWithDiscountField = value;
                    this.RaisePropertyChanged("FullPriceWithDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FullPriceWithoutDiscount {
            get {
                return this.FullPriceWithoutDiscountField;
            }
            set {
                if ((this.FullPriceWithoutDiscountField.Equals(value) != true)) {
                    this.FullPriceWithoutDiscountField = value;
                    this.RaisePropertyChanged("FullPriceWithoutDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KF.KFWCFServiceLibrary.Insurance[] Insurances {
            get {
                return this.InsurancesField;
            }
            set {
                if ((object.ReferenceEquals(this.InsurancesField, value) != true)) {
                    this.InsurancesField = value;
                    this.RaisePropertyChanged("Insurances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SeniorityDiscount {
            get {
                return this.SeniorityDiscountField;
            }
            set {
                if ((this.SeniorityDiscountField.Equals(value) != true)) {
                    this.SeniorityDiscountField = value;
                    this.RaisePropertyChanged("SeniorityDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalDiscount {
            get {
                return this.TotalDiscountField;
            }
            set {
                if ((this.TotalDiscountField.Equals(value) != true)) {
                    this.TotalDiscountField = value;
                    this.RaisePropertyChanged("TotalDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double YearsWithoutCrashDiscount {
            get {
                return this.YearsWithoutCrashDiscountField;
            }
            set {
                if ((this.YearsWithoutCrashDiscountField.Equals(value) != true)) {
                    this.YearsWithoutCrashDiscountField = value;
                    this.RaisePropertyChanged("YearsWithoutCrashDiscount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/KFWCFServiceLibrary.Models")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ExtraEquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> HasYellowPlatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NewPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ExtraEquipment {
            get {
                return this.ExtraEquipmentField;
            }
            set {
                if ((this.ExtraEquipmentField.Equals(value) != true)) {
                    this.ExtraEquipmentField = value;
                    this.RaisePropertyChanged("ExtraEquipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HasYellowPlates {
            get {
                return this.HasYellowPlatesField;
            }
            set {
                if ((this.HasYellowPlatesField.Equals(value) != true)) {
                    this.HasYellowPlatesField = value;
                    this.RaisePropertyChanged("HasYellowPlates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NewPrice {
            get {
                return this.NewPriceField;
            }
            set {
                if ((this.NewPriceField.Equals(value) != true)) {
                    this.NewPriceField = value;
                    this.RaisePropertyChanged("NewPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNr {
            get {
                return this.RegNrField;
            }
            set {
                if ((object.ReferenceEquals(this.RegNrField, value) != true)) {
                    this.RegNrField = value;
                    this.RaisePropertyChanged("RegNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/KFWCFServiceLibrary.Models")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CprNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeniorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearsWithoutCrashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZipcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CprNr {
            get {
                return this.CprNrField;
            }
            set {
                if ((this.CprNrField.Equals(value) != true)) {
                    this.CprNrField = value;
                    this.RaisePropertyChanged("CprNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivateCustomer {
            get {
                return this.IsPrivateCustomerField;
            }
            set {
                if ((this.IsPrivateCustomerField.Equals(value) != true)) {
                    this.IsPrivateCustomerField = value;
                    this.RaisePropertyChanged("IsPrivateCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Seniority {
            get {
                return this.SeniorityField;
            }
            set {
                if ((this.SeniorityField.Equals(value) != true)) {
                    this.SeniorityField = value;
                    this.RaisePropertyChanged("Seniority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearsWithoutCrash {
            get {
                return this.YearsWithoutCrashField;
            }
            set {
                if ((this.YearsWithoutCrashField.Equals(value) != true)) {
                    this.YearsWithoutCrashField = value;
                    this.RaisePropertyChanged("YearsWithoutCrash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Zipcode {
            get {
                return this.ZipcodeField;
            }
            set {
                if ((this.ZipcodeField.Equals(value) != true)) {
                    this.ZipcodeField = value;
                    this.RaisePropertyChanged("Zipcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insurance", Namespace="http://schemas.datacontract.org/2004/07/KFWCFServiceLibrary.Models")]
    [System.SerializableAttribute()]
    public partial class Insurance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KFWCFServiceLibrary.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateInsurance", ReplyAction="http://tempuri.org/IService1/CalculateInsuranceResponse")]
        KF.KFWCFServiceLibrary.InsuranceCalc CalculateInsurance(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateInsurance", ReplyAction="http://tempuri.org/IService1/CalculateInsuranceResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.InsuranceCalc> CalculateInsuranceAsync(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCar", ReplyAction="http://tempuri.org/IService1/GetCarResponse")]
        KF.KFWCFServiceLibrary.Car GetCar(string regNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCar", ReplyAction="http://tempuri.org/IService1/GetCarResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Car> GetCarAsync(string regNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInsurances", ReplyAction="http://tempuri.org/IService1/GetInsurancesResponse")]
        KF.KFWCFServiceLibrary.Insurance[] GetInsurances();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInsurances", ReplyAction="http://tempuri.org/IService1/GetInsurancesResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Insurance[]> GetInsurancesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExcess", ReplyAction="http://tempuri.org/IService1/GetExcessResponse")]
        int GetExcess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExcess", ReplyAction="http://tempuri.org/IService1/GetExcessResponse")]
        System.Threading.Tasks.Task<int> GetExcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomer", ReplyAction="http://tempuri.org/IService1/GetCustomerResponse")]
        KF.KFWCFServiceLibrary.Customer GetCustomer(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomer", ReplyAction="http://tempuri.org/IService1/GetCustomerResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Customer> GetCustomerAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOffers", ReplyAction="http://tempuri.org/IService1/GetOffersResponse")]
        KF.KFWCFServiceLibrary.InsuranceCalc[] GetOffers(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOffers", ReplyAction="http://tempuri.org/IService1/GetOffersResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.InsuranceCalc[]> GetOffersAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveOffer", ReplyAction="http://tempuri.org/IService1/SaveOfferResponse")]
        bool SaveOffer(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveOffer", ReplyAction="http://tempuri.org/IService1/SaveOfferResponse")]
        System.Threading.Tasks.Task<bool> SaveOfferAsync(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : KF.KFWCFServiceLibrary.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<KF.KFWCFServiceLibrary.IService1>, KF.KFWCFServiceLibrary.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KF.KFWCFServiceLibrary.InsuranceCalc CalculateInsurance(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc) {
            return base.Channel.CalculateInsurance(insuranceCalc);
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.InsuranceCalc> CalculateInsuranceAsync(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc) {
            return base.Channel.CalculateInsuranceAsync(insuranceCalc);
        }
        
        public KF.KFWCFServiceLibrary.Car GetCar(string regNum) {
            return base.Channel.GetCar(regNum);
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Car> GetCarAsync(string regNum) {
            return base.Channel.GetCarAsync(regNum);
        }
        
        public KF.KFWCFServiceLibrary.Insurance[] GetInsurances() {
            return base.Channel.GetInsurances();
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Insurance[]> GetInsurancesAsync() {
            return base.Channel.GetInsurancesAsync();
        }
        
        public int GetExcess() {
            return base.Channel.GetExcess();
        }
        
        public System.Threading.Tasks.Task<int> GetExcessAsync() {
            return base.Channel.GetExcessAsync();
        }
        
        public KF.KFWCFServiceLibrary.Customer GetCustomer(int customerId) {
            return base.Channel.GetCustomer(customerId);
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Customer> GetCustomerAsync(int customerId) {
            return base.Channel.GetCustomerAsync(customerId);
        }
        
        public KF.KFWCFServiceLibrary.InsuranceCalc[] GetOffers(int customerId) {
            return base.Channel.GetOffers(customerId);
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.InsuranceCalc[]> GetOffersAsync(int customerId) {
            return base.Channel.GetOffersAsync(customerId);
        }
        
        public bool SaveOffer(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc) {
            return base.Channel.SaveOffer(insuranceCalc);
        }
        
        public System.Threading.Tasks.Task<bool> SaveOfferAsync(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc) {
            return base.Channel.SaveOfferAsync(insuranceCalc);
        }
    }
}
