//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateInsurance", ReplyAction="http://tempuri.org/IService1/CalculateInsuranceResponse")]
        KF.KFWCFServiceLibrary.InsuranceCalc CalculateInsurance(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateInsurance", ReplyAction="http://tempuri.org/IService1/CalculateInsuranceResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.InsuranceCalc> CalculateInsuranceAsync(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCar", ReplyAction="http://tempuri.org/IService1/GetCarResponse")]
        KF.KFWCFServiceLibrary.Car GetCar(string regNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCar", ReplyAction="http://tempuri.org/IService1/GetCarResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Car> GetCarAsync(string regNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInsurances", ReplyAction="http://tempuri.org/IService1/GetInsurancesResponse")]
        KF.KFWCFServiceLibrary.Insurance[] GetInsurances();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInsurances", ReplyAction="http://tempuri.org/IService1/GetInsurancesResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Insurance[]> GetInsurancesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExcess", ReplyAction="http://tempuri.org/IService1/GetExcessResponse")]
        int GetExcess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExcess", ReplyAction="http://tempuri.org/IService1/GetExcessResponse")]
        System.Threading.Tasks.Task<int> GetExcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomer", ReplyAction="http://tempuri.org/IService1/GetCustomerResponse")]
        KF.KFWCFServiceLibrary.Customer GetCustomer(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomer", ReplyAction="http://tempuri.org/IService1/GetCustomerResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Customer> GetCustomerAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOffers", ReplyAction="http://tempuri.org/IService1/GetOffersResponse")]
        KF.KFWCFServiceLibrary.InsuranceCalc[] GetOffers(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOffers", ReplyAction="http://tempuri.org/IService1/GetOffersResponse")]
        System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.InsuranceCalc[]> GetOffersAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveOffer", ReplyAction="http://tempuri.org/IService1/SaveOfferResponse")]
        bool SaveOffer(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveOffer", ReplyAction="http://tempuri.org/IService1/SaveOfferResponse")]
        System.Threading.Tasks.Task<bool> SaveOfferAsync(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : KFTest.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<KFTest.ServiceReference1.IService1>, KFTest.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KF.KFWCFServiceLibrary.InsuranceCalc CalculateInsurance(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc) {
            return base.Channel.CalculateInsurance(insuranceCalc);
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.InsuranceCalc> CalculateInsuranceAsync(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc) {
            return base.Channel.CalculateInsuranceAsync(insuranceCalc);
        }
        
        public KF.KFWCFServiceLibrary.Car GetCar(string regNum) {
            return base.Channel.GetCar(regNum);
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Car> GetCarAsync(string regNum) {
            return base.Channel.GetCarAsync(regNum);
        }
        
        public KF.KFWCFServiceLibrary.Insurance[] GetInsurances() {
            return base.Channel.GetInsurances();
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Insurance[]> GetInsurancesAsync() {
            return base.Channel.GetInsurancesAsync();
        }
        
        public int GetExcess() {
            return base.Channel.GetExcess();
        }
        
        public System.Threading.Tasks.Task<int> GetExcessAsync() {
            return base.Channel.GetExcessAsync();
        }
        
        public KF.KFWCFServiceLibrary.Customer GetCustomer(int customerId) {
            return base.Channel.GetCustomer(customerId);
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.Customer> GetCustomerAsync(int customerId) {
            return base.Channel.GetCustomerAsync(customerId);
        }
        
        public KF.KFWCFServiceLibrary.InsuranceCalc[] GetOffers(int customerId) {
            return base.Channel.GetOffers(customerId);
        }
        
        public System.Threading.Tasks.Task<KF.KFWCFServiceLibrary.InsuranceCalc[]> GetOffersAsync(int customerId) {
            return base.Channel.GetOffersAsync(customerId);
        }
        
        public bool SaveOffer(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc) {
            return base.Channel.SaveOffer(insuranceCalc);
        }
        
        public System.Threading.Tasks.Task<bool> SaveOfferAsync(KF.KFWCFServiceLibrary.InsuranceCalc insuranceCalc) {
            return base.Channel.SaveOfferAsync(insuranceCalc);
        }
    }
}
